# fly.toml app configuration file generated for reactivitiesdabuleanu on 2024-03-23T21:39:38+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'reactivitiesdabuleanu'
primary_region = 'otp'

[build]
  image = 'alexandrudabuleanu/reactivities:latest'

[env]
  ASPNETCORE_URLS="http://+:8080"
  Cloudinary__CloudName="dzcbnpola"
  Cloudinary__ApiKey="185943577893818"
  Facebook__AppId="2606893589490075"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
